name: surf_flutter_study_jam_2023
description: Surf Flutter Study Jam 2023.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  theme_tailor_annotation: ^1.1.1

  google_fonts: ^4.0.3
  device_preview: ^1.1.0
  url_launcher: ^6.1.10

  flutter_riverpod: ^2.3.4
  dio: ^5.1.1
  path_provider: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  theme_tailor: ^1.1.2
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  custom_lint: ^0.3.3
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true